name: army codes updater

on:
  push:
    branches: [ main ]
    paths:
      - 'map.js'  # This workflow will only run when map.js is updated

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If there are any dependencies, install them here
    - name: Run Python script
      run: python army_code.py
    - name: Commit and push changes
      run: |
        git config --global user.name 'df44-1411'
        git config --global user.email 'df2016tic@gmail.com'
        git add .
        git commit -m "Update army_code.html"
        git push
